#docker compose -f docker-compose-cluster.yml up -d

version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
#    volumes:
#      - "/Users/lengfeng/kafka/zkcluster/zoo1/data:/data"
#      - "/Users/lengfeng/kafka/zkcluster/zoo1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
  #        networks:
  #            kafka:
  #                ipv4_address: 172.30.0.11

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
#    volumes:
#      - "/Users/lengfeng/kafka/zkcluster/zoo2/data:/data"
#      - "/Users/lengfeng/kafka/zkcluster/zoo2/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    #        networks:
    #            kafka:
    #                ipv4_address: 172.30.0.12

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
#    volumes:
#      - "/Users/lengfeng/kafka/zkcluster/zoo3/data:/data"
#      - "/Users/lengfeng/kafka/zkcluster/zoo3/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
#        networks:
#            kafka:
#                ipv4_address: 172.30.0.13

#networks:
#    kafka:
#        external:
#            name: kafka
